
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: "142213bi"

development:
  <<: *default
  database: todo-list_development


test:
  <<: *default
  database: todo-list_test

production:
  <<: *default
  database: todo-list_production
  password: <%= ENV['TODO-LIST_DATABASE_PASSWORD'] %>
